FROM java

LABEL maintainer "misha.yang@daocloud.io"

COPY /project/target/Spring-Boot-0.0.1-SNAPSHOT.jar  /usr/src/myapp/Spring-Boot-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar Spring-Boot-0.0.1-SNAPSHOT.jar