
package com.gtms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-29T17:12:02.747+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class CouponBindService_CouponBindImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gtms.com/", "CouponBindImplService");

    private CouponBindService_CouponBindImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CouponBindImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CouponBindImplService ss = new CouponBindImplService(wsdlURL, SERVICE_NAME);
        CouponBindService port = ss.getCouponBindImplPort();  
        
        {
        System.out.println("Invoking getCouponBind...");
        com.gtms.CoupBindIn _getCouponBind_parmInput = null;
        com.gtms.CoupBindOut _getCouponBind__return = port.getCouponBind(_getCouponBind_parmInput);
        System.out.println("getCouponBind.result=" + _getCouponBind__return);


        }

        System.exit(0);
    }

}
