package com.gtms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-29T17:12:02.804+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://gtms.com/", name = "CouponBindService")
@XmlSeeAlso({ObjectFactory.class})
public interface CouponBindService {

    @WebResult(name = "parmOutput", targetNamespace = "")
    @RequestWrapper(localName = "getCouponBind", targetNamespace = "http://gtms.com/", className = "com.gtms.GetCouponBind")
    @WebMethod
    @ResponseWrapper(localName = "getCouponBindResponse", targetNamespace = "http://gtms.com/", className = "com.gtms.GetCouponBindResponse")
    public com.gtms.CoupBindOut getCouponBind(
        @WebParam(name = "parmInput", targetNamespace = "")
        com.gtms.CoupBindIn parmInput
    );
}
