
package com.gtms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-29T09:53:52.550+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class CoupWResultService_CoupWResultImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gtms.com/", "CoupWResultImplService");

    private CoupWResultService_CoupWResultImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CoupWResultImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CoupWResultImplService ss = new CoupWResultImplService(wsdlURL, SERVICE_NAME);
        CoupWResultService port = ss.getCoupWResultImplPort();  
        
        {
        System.out.println("Invoking getCoupWResult...");
        com.gtms.CouponWOffIn _getCoupWResult_parmInput = null;
        com.gtms.CoupWOffOut _getCoupWResult__return = port.getCoupWResult(_getCoupWResult_parmInput);
        System.out.println("getCoupWResult.result=" + _getCoupWResult__return);


        }

        System.exit(0);
    }

}
