package com.gtms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-29T17:12:02.810+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "CouponBindImplService", 
                  wsdlLocation = "file:/D:/广汽丰田/Iclub/couponServiceXML/getCouponBind.xml",
                  targetNamespace = "http://gtms.com/") 
public class CouponBindImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gtms.com/", "CouponBindImplService");
    public final static QName CouponBindImplPort = new QName("http://gtms.com/", "CouponBindImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/广汽丰田/Iclub/couponServiceXML/getCouponBind.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CouponBindImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/广汽丰田/Iclub/couponServiceXML/getCouponBind.xml");
        }
        WSDL_LOCATION = url;
    }

    public CouponBindImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CouponBindImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CouponBindImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CouponBindImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CouponBindImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CouponBindImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CouponBindService
     */
    @WebEndpoint(name = "CouponBindImplPort")
    public CouponBindService getCouponBindImplPort() {
        return super.getPort(CouponBindImplPort, CouponBindService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CouponBindService
     */
    @WebEndpoint(name = "CouponBindImplPort")
    public CouponBindService getCouponBindImplPort(WebServiceFeature... features) {
        return super.getPort(CouponBindImplPort, CouponBindService.class, features);
    }

}
