
package com.gtms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-05-11T10:42:27.767+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class GetMsgContentService_GetMsgContentServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gtms.com/", "GetMsgContentServiceImplService");

    private GetMsgContentService_GetMsgContentServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetMsgContentServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetMsgContentServiceImplService ss = new GetMsgContentServiceImplService(wsdlURL, SERVICE_NAME);
        GetMsgContentService port = ss.getGetMsgContentServiceImplPort();  
        
        {
        System.out.println("Invoking getMsgContent...");
        com.gtms.GetMsgContentInput _getMsgContent_parmInput = null;
        com.gtms.GetMsgContentOutput _getMsgContent__return = port.getMsgContent(_getMsgContent_parmInput);
        System.out.println("getMsgContent.result=" + _getMsgContent__return);


        }

        System.exit(0);
    }

}
