package com.gtms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-05-11T10:42:27.889+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "GetMsgContentServiceImplService", 
                  wsdlLocation = "file:/D:/test/GetMsgContent.xml",
                  targetNamespace = "http://gtms.com/") 
public class GetMsgContentServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gtms.com/", "GetMsgContentServiceImplService");
    public final static QName GetMsgContentServiceImplPort = new QName("http://gtms.com/", "GetMsgContentServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/test/GetMsgContent.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetMsgContentServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/test/GetMsgContent.xml");
        }
        WSDL_LOCATION = url;
    }

    public GetMsgContentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetMsgContentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetMsgContentServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetMsgContentServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetMsgContentServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetMsgContentServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetMsgContentService
     */
    @WebEndpoint(name = "GetMsgContentServiceImplPort")
    public GetMsgContentService getGetMsgContentServiceImplPort() {
        return super.getPort(GetMsgContentServiceImplPort, GetMsgContentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetMsgContentService
     */
    @WebEndpoint(name = "GetMsgContentServiceImplPort")
    public GetMsgContentService getGetMsgContentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GetMsgContentServiceImplPort, GetMsgContentService.class, features);
    }

}
