package com.gtms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2017-04-17T16:12:50.090+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://gtms.com/", name = "GetTempletMsgService")
@XmlSeeAlso({ObjectFactory.class})
public interface GetTempletMsgService {

    @WebResult(name = "parmOutput", targetNamespace = "")
    @RequestWrapper(localName = "getTempletMsgInfo", targetNamespace = "http://gtms.com/", className = "com.gtms.GetTempletMsgInfo")
    @WebMethod
    @ResponseWrapper(localName = "getTempletMsgInfoResponse", targetNamespace = "http://gtms.com/", className = "com.gtms.GetTempletMsgInfoResponse")
    public com.gtms.GetTempletMsgOutput getTempletMsgInfo(
        @WebParam(name = "parmInput", targetNamespace = "")
        com.gtms.GetTempletMsgInput parmInput
    );
}
