
package com.gtms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2017-12-20T21:32:09.362+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class GetUserIdTelService_GetUserIdTelServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gtms.com/", "GetUserIdTelServiceImplService");

    private GetUserIdTelService_GetUserIdTelServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetUserIdTelServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetUserIdTelServiceImplService ss = new GetUserIdTelServiceImplService(wsdlURL, SERVICE_NAME);
        GetUserIdTelService port = ss.getGetUserIdTelServiceImplPort();  
        
        {
        System.out.println("Invoking getUserInfo...");
        com.gtms.GetUserIdTelInput _getUserInfo_parmInput = null;
        com.gtms.GetUserIdTelOutput _getUserInfo__return = port.getUserInfo(_getUserInfo_parmInput);
        System.out.println("getUserInfo.result=" + _getUserInfo__return);


        }

        System.exit(0);
    }

}
