package com.gtms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2017-12-20T21:32:09.428+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "GetUserIdTelServiceImplService", 
                  wsdlLocation = "file:/d:/GetUserInfo.wsdl",
                  targetNamespace = "http://gtms.com/") 
public class GetUserIdTelServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gtms.com/", "GetUserIdTelServiceImplService");
    public final static QName GetUserIdTelServiceImplPort = new QName("http://gtms.com/", "GetUserIdTelServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/GetUserInfo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetUserIdTelServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/GetUserInfo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetUserIdTelServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetUserIdTelServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUserIdTelServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetUserIdTelService
     */
    @WebEndpoint(name = "GetUserIdTelServiceImplPort")
    public GetUserIdTelService getGetUserIdTelServiceImplPort() {
        return super.getPort(GetUserIdTelServiceImplPort, GetUserIdTelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUserIdTelService
     */
    @WebEndpoint(name = "GetUserIdTelServiceImplPort")
    public GetUserIdTelService getGetUserIdTelServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GetUserIdTelServiceImplPort, GetUserIdTelService.class, features);
    }

}
