package com.gtms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-28T17:30:28.798+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://gtms.com/", name = "MemberPhoneValidateService")
@XmlSeeAlso({ObjectFactory.class})
public interface MemberPhoneValidateService {

    @WebResult(name = "parmOutput", targetNamespace = "")
    @RequestWrapper(localName = "getPhoneValidateInfo", targetNamespace = "http://gtms.com/", className = "com.gtms.GetPhoneValidateInfo")
    @WebMethod
    @ResponseWrapper(localName = "getPhoneValidateInfoResponse", targetNamespace = "http://gtms.com/", className = "com.gtms.GetPhoneValidateInfoResponse")
    public com.gtms.MemberPhoneValidateInfoOutput getPhoneValidateInfo(
        @WebParam(name = "parmInput", targetNamespace = "")
        com.gtms.MemberPhoneValidateInfoInput parmInput
    );
}
