package com.gtms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-28T17:30:28.811+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "MemberPhoneValidateServiceImplService", 
                  wsdlLocation = "file:/D:/getPhoneValidateInfo.xml",
                  targetNamespace = "http://gtms.com/") 
public class MemberPhoneValidateServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gtms.com/", "MemberPhoneValidateServiceImplService");
    public final static QName MemberPhoneValidateServiceImplPort = new QName("http://gtms.com/", "MemberPhoneValidateServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/getPhoneValidateInfo.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MemberPhoneValidateServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/getPhoneValidateInfo.xml");
        }
        WSDL_LOCATION = url;
    }

    public MemberPhoneValidateServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MemberPhoneValidateServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberPhoneValidateServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MemberPhoneValidateServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MemberPhoneValidateServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MemberPhoneValidateServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MemberPhoneValidateService
     */
    @WebEndpoint(name = "MemberPhoneValidateServiceImplPort")
    public MemberPhoneValidateService getMemberPhoneValidateServiceImplPort() {
        return super.getPort(MemberPhoneValidateServiceImplPort, MemberPhoneValidateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberPhoneValidateService
     */
    @WebEndpoint(name = "MemberPhoneValidateServiceImplPort")
    public MemberPhoneValidateService getMemberPhoneValidateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MemberPhoneValidateServiceImplPort, MemberPhoneValidateService.class, features);
    }

}
