
package com.gtms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-04-28T17:30:28.623+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class MemberPhoneValidateService_MemberPhoneValidateServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gtms.com/", "MemberPhoneValidateServiceImplService");

    private MemberPhoneValidateService_MemberPhoneValidateServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MemberPhoneValidateServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MemberPhoneValidateServiceImplService ss = new MemberPhoneValidateServiceImplService(wsdlURL, SERVICE_NAME);
        MemberPhoneValidateService port = ss.getMemberPhoneValidateServiceImplPort();  
        
        {
        System.out.println("Invoking getPhoneValidateInfo...");
        com.gtms.MemberPhoneValidateInfoInput _getPhoneValidateInfo_parmInput = new com.gtms.MemberPhoneValidateInfoInput();
        com.gtms.MemberPhoneValidateInfoOutput _getPhoneValidateInfo__return = port.getPhoneValidateInfo(_getPhoneValidateInfo_parmInput);
        System.out.println("getPhoneValidateInfo.result=" + _getPhoneValidateInfo__return);


        }

        System.exit(0);
    }

}
