
package com.gtms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2017-04-13T13:43:52.707+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class RankUpGiftService_RankUpGiftServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gtms.com/", "RankUpGiftServiceImplService");

    private RankUpGiftService_RankUpGiftServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RankUpGiftServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RankUpGiftServiceImplService ss = new RankUpGiftServiceImplService(wsdlURL, SERVICE_NAME);
        RankUpGiftService port = ss.getRankUpGiftServiceImplPort();  
        
        {
        System.out.println("Invoking getRankUpGift...");
        com.gtms.RankUpGiftIn _getRankUpGift_parmInput = null;
        com.gtms.RankUpGiftOut _getRankUpGift__return = port.getRankUpGift(_getRankUpGift_parmInput);
        System.out.println("getRankUpGift.result=" + _getRankUpGift__return);


        }

        System.exit(0);
    }

}
