package com.gtms;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2017-04-13T13:43:53.234+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "RankUpGiftServiceImplService", 
                  wsdlLocation = "getRankUpGift.wsdl",
                  targetNamespace = "http://gtms.com/") 
public class RankUpGiftServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gtms.com/", "RankUpGiftServiceImplService");
    public final static QName RankUpGiftServiceImplPort = new QName("http://gtms.com/", "RankUpGiftServiceImplPort");
    static {
        URL url = RankUpGiftServiceImplService.class.getResource("getRankUpGift.wsdl");
        if (url == null) {
            url = RankUpGiftServiceImplService.class.getClassLoader().getResource("getRankUpGift.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(RankUpGiftServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "getRankUpGift.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public RankUpGiftServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RankUpGiftServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RankUpGiftServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RankUpGiftService
     */
    @WebEndpoint(name = "RankUpGiftServiceImplPort")
    public RankUpGiftService getRankUpGiftServiceImplPort() {
        return super.getPort(RankUpGiftServiceImplPort, RankUpGiftService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RankUpGiftService
     */
    @WebEndpoint(name = "RankUpGiftServiceImplPort")
    public RankUpGiftService getRankUpGiftServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RankUpGiftServiceImplPort, RankUpGiftService.class, features);
    }

}
