package com.yonyou.est.webservice.coupon;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-12-04T15:44:59.849+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "CouponWebServiceService", 
                  wsdlLocation = "http://signin.gtmc.com.cn/WXESTS/services/couponWebService?wsdl",
                  targetNamespace = "http://coupon.webService.est.yonyou.com/") 
public class CouponWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://coupon.webService.est.yonyou.com/", "CouponWebServiceService");
    public final static QName CouponWebServicePort = new QName("http://coupon.webService.est.yonyou.com/", "CouponWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://signin.gtmc.com.cn/WXESTS/services/couponWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CouponWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://signin.gtmc.com.cn/WXESTS/services/couponWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CouponWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CouponWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CouponWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CouponWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CouponWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CouponWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICouponWebService
     */
    @WebEndpoint(name = "CouponWebServicePort")
    public ICouponWebService getCouponWebServicePort() {
        return super.getPort(CouponWebServicePort, ICouponWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICouponWebService
     */
    @WebEndpoint(name = "CouponWebServicePort")
    public ICouponWebService getCouponWebServicePort(WebServiceFeature... features) {
        return super.getPort(CouponWebServicePort, ICouponWebService.class, features);
    }

}
