
package com.yonyou.est.webservice.coupon;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-12-04T15:44:59.800+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class ICouponWebService_CouponWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://coupon.webService.est.yonyou.com/", "CouponWebServiceService");

    private ICouponWebService_CouponWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CouponWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CouponWebServiceService ss = new CouponWebServiceService(wsdlURL, SERVICE_NAME);
        ICouponWebService port = ss.getCouponWebServicePort();  
        
        {
        System.out.println("Invoking offsetCoupon...");
        java.lang.String _offsetCoupon_couponId = "";
        com.yonyou.est.webservice.coupon.OffsetCouponResponseEntity _offsetCoupon__return = port.offsetCoupon(_offsetCoupon_couponId);
        System.out.println("offsetCoupon.result=" + _offsetCoupon__return);


        }
        {
        System.out.println("Invoking useCoupon...");
        java.lang.String _useCoupon_couponId = "";
        java.lang.String _useCoupon_couponStatus = "";
        com.yonyou.est.webservice.coupon.UseCouponResponseEntity _useCoupon__return = port.useCoupon(_useCoupon_couponId, _useCoupon_couponStatus);
        System.out.println("useCoupon.result=" + _useCoupon__return);


        }
        {
        System.out.println("Invoking varifyCoupon...");
        java.lang.String _varifyCoupon_couponId = "";
        com.yonyou.est.webservice.coupon.CouponVerifyResponse _varifyCoupon__return = port.varifyCoupon(_varifyCoupon_couponId);
        System.out.println("varifyCoupon.result=" + _varifyCoupon__return);


        }
        {
        System.out.println("Invoking getCouponList...");
        java.lang.String _getCouponList_startTime = "";
        com.yonyou.est.webservice.coupon.CouponListResponse _getCouponList__return = port.getCouponList(_getCouponList_startTime);
        System.out.println("getCouponList.result=" + _getCouponList__return);


        }

        System.exit(0);
    }

}
