package com.yonyou.est.webservice.coupon;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-12-04T15:44:59.843+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://coupon.webService.est.yonyou.com/", name = "ICouponWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICouponWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "offsetCoupon", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.OffsetCoupon")
    @WebMethod
    @ResponseWrapper(localName = "offsetCouponResponse", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.OffsetCouponResponse")
    public com.yonyou.est.webservice.coupon.OffsetCouponResponseEntity offsetCoupon(
        @WebParam(name = "couponId", targetNamespace = "")
        java.lang.String couponId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "useCoupon", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.UseCoupon")
    @WebMethod
    @ResponseWrapper(localName = "useCouponResponse", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.UseCouponResponse")
    public com.yonyou.est.webservice.coupon.UseCouponResponseEntity useCoupon(
        @WebParam(name = "couponId", targetNamespace = "")
        java.lang.String couponId,
        @WebParam(name = "couponStatus", targetNamespace = "")
        java.lang.String couponStatus
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "varifyCoupon", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.VarifyCoupon")
    @WebMethod
    @ResponseWrapper(localName = "varifyCouponResponse", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.VarifyCouponResponse")
    public com.yonyou.est.webservice.coupon.CouponVerifyResponse varifyCoupon(
        @WebParam(name = "couponId", targetNamespace = "")
        java.lang.String couponId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCouponList", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.GetCouponList")
    @WebMethod
    @ResponseWrapper(localName = "getCouponListResponse", targetNamespace = "http://coupon.webService.est.yonyou.com/", className = "com.yonyou.est.webservice.coupon.GetCouponListResponse")
    public com.yonyou.est.webservice.coupon.CouponListResponse getCouponList(
        @WebParam(name = "startTime", targetNamespace = "")
        java.lang.String startTime
    );
}
