
package com.tlan.webservice.ibpp.impl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-06-06T10:53:44.656+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class OutwardSerivceImpl_OutwardSerivceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.IBPP.webservice.tlan.com/", "OutwardSerivceImplService");

    private OutwardSerivceImpl_OutwardSerivceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OutwardSerivceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OutwardSerivceImplService ss = new OutwardSerivceImplService(wsdlURL, SERVICE_NAME);
        OutwardSerivceImpl port = ss.getOutwardSerivceImplPort();  
        
        {
        System.out.println("Invoking sendredpack...");
        com.tlan.webservice.ibpp.impl.RedPackInput _sendredpack_arg0 = null;
        com.tlan.webservice.ibpp.impl.RedPackOutput _sendredpack__return = port.sendredpack(_sendredpack_arg0);
        System.out.println("sendredpack.result=" + _sendredpack__return);


        }

        System.exit(0);
    }

}
