package com.tlan.webservice.ibpp.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-06-06T10:53:44.686+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://impl.IBPP.webservice.tlan.com/", name = "OutwardSerivceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface OutwardSerivceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://impl.IBPP.webservice.tlan.com/OutwardSerivceImpl/sendredpackRequest", output = "http://impl.IBPP.webservice.tlan.com/OutwardSerivceImpl/sendredpackResponse")
    @RequestWrapper(localName = "sendredpack", targetNamespace = "http://impl.IBPP.webservice.tlan.com/", className = "com.tlan.webservice.ibpp.impl.Sendredpack")
    @WebMethod
    @ResponseWrapper(localName = "sendredpackResponse", targetNamespace = "http://impl.IBPP.webservice.tlan.com/", className = "com.tlan.webservice.ibpp.impl.SendredpackResponse")
    public com.tlan.webservice.ibpp.impl.RedPackOutput sendredpack(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tlan.webservice.ibpp.impl.RedPackInput arg0
    );
}
